#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : kdiamond
Version  : 19.08.1
Release  : 16
URL      : https://download.kde.org/stable/applications/19.08.1/src/kdiamond-19.08.1.tar.xz
Source0  : https://download.kde.org/stable/applications/19.08.1/src/kdiamond-19.08.1.tar.xz
Source1 : https://download.kde.org/stable/applications/19.08.1/src/kdiamond-19.08.1.tar.xz.sig
Summary  : A single player puzzle game
Group    : Development/Tools
License  : GFDL-1.2 GPL-2.0
Requires: kdiamond-bin = %{version}-%{release}
Requires: kdiamond-data = %{version}-%{release}
Requires: kdiamond-license = %{version}-%{release}
Requires: kdiamond-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : knotifyconfig-dev
BuildRequires : libkdegames-dev
BuildRequires : qtbase-dev mesa-dev

%description
No detailed description available

%package bin
Summary: bin components for the kdiamond package.
Group: Binaries
Requires: kdiamond-data = %{version}-%{release}
Requires: kdiamond-license = %{version}-%{release}

%description bin
bin components for the kdiamond package.


%package data
Summary: data components for the kdiamond package.
Group: Data

%description data
data components for the kdiamond package.


%package doc
Summary: doc components for the kdiamond package.
Group: Documentation

%description doc
doc components for the kdiamond package.


%package license
Summary: license components for the kdiamond package.
Group: Default

%description license
license components for the kdiamond package.


%package locales
Summary: locales components for the kdiamond package.
Group: Default

%description locales
locales components for the kdiamond package.


%prep
%setup -q -n kdiamond-19.08.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567699960
mkdir -p clr-build
pushd clr-build
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1567699960
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kdiamond
cp COPYING %{buildroot}/usr/share/package-licenses/kdiamond/COPYING
cp COPYING.DOC %{buildroot}/usr/share/package-licenses/kdiamond/COPYING.DOC
pushd clr-build
%make_install
popd
%find_lang kdiamond

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kdiamond

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.kdiamond.desktop
/usr/share/icons/hicolor/128x128/apps/kdiamond.png
/usr/share/icons/hicolor/16x16/apps/kdiamond.png
/usr/share/icons/hicolor/22x22/apps/kdiamond.png
/usr/share/icons/hicolor/32x32/apps/kdiamond.png
/usr/share/icons/hicolor/48x48/apps/kdiamond.png
/usr/share/icons/hicolor/64x64/apps/kdiamond.png
/usr/share/kdiamond/kdiamond.kcfg
/usr/share/kdiamond/themes/default.desktop
/usr/share/kdiamond/themes/diamonds.desktop
/usr/share/kdiamond/themes/diamonds.png
/usr/share/kdiamond/themes/diamonds.svgz
/usr/share/kdiamond/themes/egyptian.svgz
/usr/share/kdiamond/themes/egyptian_preview.png
/usr/share/kdiamond/themes/funny_zoo.desktop
/usr/share/kdiamond/themes/funny_zoo.png
/usr/share/kdiamond/themes/funny_zoo.svgz
/usr/share/knotifications5/kdiamond.notifyrc
/usr/share/kxmlgui5/kdiamond/kdiamondui.rc
/usr/share/metainfo/org.kde.kdiamond.appdata.xml
/usr/share/sounds/KDiamond-Stone-Drop.ogg
/usr/share/sounds/KDiamond-Stone-Swap.ogg
/usr/share/sounds/KDiamond-Stone-Touch.ogg
/usr/share/xdg/kdiamond.knsrc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/de/kdiamond/index.cache.bz2
/usr/share/doc/HTML/de/kdiamond/index.docbook
/usr/share/doc/HTML/en/kdiamond/gameboard.png
/usr/share/doc/HTML/en/kdiamond/index.cache.bz2
/usr/share/doc/HTML/en/kdiamond/index.docbook
/usr/share/doc/HTML/es/kdiamond/index.cache.bz2
/usr/share/doc/HTML/es/kdiamond/index.docbook
/usr/share/doc/HTML/et/kdiamond/index.cache.bz2
/usr/share/doc/HTML/et/kdiamond/index.docbook
/usr/share/doc/HTML/fr/kdiamond/index.cache.bz2
/usr/share/doc/HTML/fr/kdiamond/index.docbook
/usr/share/doc/HTML/it/kdiamond/index.cache.bz2
/usr/share/doc/HTML/it/kdiamond/index.docbook
/usr/share/doc/HTML/lt/kdiamond/index.cache.bz2
/usr/share/doc/HTML/lt/kdiamond/index.docbook
/usr/share/doc/HTML/nl/kdiamond/index.cache.bz2
/usr/share/doc/HTML/nl/kdiamond/index.docbook
/usr/share/doc/HTML/pl/kdiamond/index.cache.bz2
/usr/share/doc/HTML/pl/kdiamond/index.docbook
/usr/share/doc/HTML/pt/kdiamond/index.cache.bz2
/usr/share/doc/HTML/pt/kdiamond/index.docbook
/usr/share/doc/HTML/pt_BR/kdiamond/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kdiamond/index.docbook
/usr/share/doc/HTML/sv/kdiamond/index.cache.bz2
/usr/share/doc/HTML/sv/kdiamond/index.docbook
/usr/share/doc/HTML/uk/kdiamond/gameboard.png
/usr/share/doc/HTML/uk/kdiamond/index.cache.bz2
/usr/share/doc/HTML/uk/kdiamond/index.docbook

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kdiamond/COPYING
/usr/share/package-licenses/kdiamond/COPYING.DOC

%files locales -f kdiamond.lang
%defattr(-,root,root,-)

